__meta__:
  kind: fragment
  version: "260409"
  date: "2026-04-09"
  description: ND-LAr 260409 standalone shower GrapPA model

include: model/common/grappa_shower/base_v1.yaml

override:
  model.modules.grappa: !include model/nd-lar/grappa_shower/network_260409.yaml
  model.modules.grappa_loss: !include model/nd-lar/grappa_shower/loss_260409.yaml
