__meta__:
  kind: fragment
  version: "250505"
  date: "2025-05-05"
  description: ND-LAr 250505 shower GrapPA network

include: model/common/grappa_shower/network_v1.yaml

override:
  graph.max_length: [500, 0, 500, 500, 0, 0, 0, 25, 0, 25]
  node_encoder.dir_max_dist: -1
  node_encoder.dedx_max_dist: -1
