__meta__:
  kind: fragment
  version: "260310"
  date: "2026-03-10"
  description: ND-LAr 260310 shower GrapPA network

include: model/common/grappa_shower/network_v1.yaml

override:
  graph.max_length: [400, 0, 400, 400, 0, 0, 0, 20, 0, 20]
