# ProtoDUNE-SP model configuration
# Revision date: February 10, 2026

__meta__:
  kind: bundle
  version: "260210"
  date: "2026-02-10"
  description: "ProtoDUNE-SP collection-only model with in-chain calibration, v0 dataset"
  compatible_with:
    base: ">=260210"
    io: ">=260210"
  tags:
    [
      collection-only,
      pre-calibration,
      ppn-restrict,
      grappa-use-closest,
      grouping-through-track,
    ]
  training_set: "v0"

include: model/protodune-sp/full_chain/model_260210.yaml

override:
  # Path to the first full chain model weights
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/protodune-sp/protodune-sp_snapshot_260210.ckpt
    hash: 38341f8a948c28c7f83e9241247785015002fd7009b3ac8b4dae6be320b70227
