__meta__:
  kind: fragment
  version: "240819"
  date: "2024-08-19"
  description: ND-LAr 240819 standalone UResNet-PPN model

include: model/common/uresnet_ppn/base_v1.yaml

override:
  model.modules.uresnet: !include model/nd-lar/uresnet/network_240819.yaml
  model.modules.ppn: !include model/common/uresnet_ppn/ppn_v1.yaml
  model.modules.uresnet_loss: !include model/nd-lar/uresnet/loss_240819.yaml
  model.modules.ppn_loss: !include model/common/uresnet_ppn/ppn_loss_v1.yaml
