__meta__:
  kind: fragment
  version: "240819"
  date: "2024-08-19"
  description: ND-LAr 240819 composed UResNet-PPN network

uresnet: !include model/nd-lar/uresnet/network_240819.yaml
ppn: !include model/common/uresnet_ppn/ppn_v1.yaml
