__meta__:
  kind: fragment
  version: "260210"
  date: "2026-02-10"
  description: ProtoDUNE-SP 260210 detector calibration

stages:
  - name: gain
    gain: 1000
  - name: recombination
    model: mbox
    efield: 0.4867
    mip_dedx: 2.105168
  - name: lifetime
    lifetime: 35000
    driftv: 0.1565
