__meta__:
  kind: bundle
  version: "260906"
  date: "2026-09-06"
  description: ProtoDUNE-SP 260906 shower GrapPA training from fragment cache

include:
  - model/protodune-sp/grappa_shower/model_260210.yaml
  - train/protodune-sp/grappa_shower/from_fragment_cache_v1.yaml
