__meta__:
  kind: fragment
  description: icarus LArCV dataset restricted to joint-overlay-compatible products

include: dataset_common.yaml

remove:
  - schema.run_info
  - schema.flashes
  - schema.crthits
