# IO common configuration for ICARUS

__meta__:
  kind: fragment

# IO configuration
io:
  loader:
    batch_size: 4
    shuffle: false
    num_workers: 8
    collate_fn:
      name: all
      split: true
      source:
        sources: sources
    dataset: !include dataset_common.yaml
  writer:
    name: hdf5
    file_name: null
    overwrite: true
    keys:
      - run_info
      - meta
      - points
      - points_label
      - points_g4
      - depositions
      - depositions_label
      - depositions_q_label
      - depositions_g4
      - sources
      - sources_label
      - reco_particles
      - truth_particles
      - reco_interactions
      - truth_interactions
      - flashes
      - crthits
