__meta__:
  kind: fragment
  version: "261007"
  date: "2026-10-07"
  description: 2x2 current full chain with overlap-aware tasks

include: model/common/full_chain/base_v1.yaml

override:
  model.modules.uresnet_ppn: !include model/2x2/uresnet_ppn/network_240819.yaml
  model.modules.uresnet_ppn_loss: !include model/2x2/uresnet_ppn/loss_261007.yaml
  model.modules.graph_spice: !include model/2x2/graph_spice/network_240819.yaml
  model.modules.graph_spice_loss: !include model/2x2/graph_spice/loss_240819.yaml
  model.modules.grappa_shower: !include model/2x2/grappa_shower/network_261007.yaml
  model.modules.grappa_shower_loss: !include model/2x2/grappa_shower/loss_261007.yaml
  model.modules.grappa_track: !include model/2x2/grappa_track/network_full_chain_261007.yaml
  model.modules.grappa_track_loss: !include model/2x2/grappa_track/loss_261007.yaml
  model.modules.grappa_inter: !include model/2x2/grappa_inter/network_full_chain_261007.yaml
  model.modules.grappa_inter_loss: !include model/2x2/grappa_inter/loss_full_chain_261007.yaml
