# ND-LAr full chain configuration
# Revision date: March 10, 2026

__meta__:
  kind: bundle
  version: "260310"
  date: "2026-03-10"
  description: "ND-LAr full chain configuration"

include:
  - base/base_240819.yaml
  - io/io_240819.yaml
  - model/model_260310.yaml
  - post/post_240819.yaml
