# ND-LAr full chain configuration
# Revision date: May 15, 2025

__meta__:
  kind: bundle
  version: "250515"
  date: "2025-05-15"
  description: "ND-LAr full chain configuration"

include:
  - base/base_240819.yaml
  - io/io_240819.yaml
  - model/model_250515.yaml
  - post/post_240819.yaml
