# Import the training configuration
include: grappa_track_edep.yaml

# Turn it into a validatio config
override:
  # Single GPU, 100 iterations
  base.world_size: 1
  base.iterations: 100
  base-: [epochs, train]

  # Single GPU batch size, no sampler, test set
  io.loader-: [sampler]
  io.loader.batch_size: 256
  io.loader.dataset.file_list: /sdf/data/neutrino/pdune/sim/vd/mpvmpr_v0/test_file_list.txt

  # Full set of weights
  #model.weight_path: /sdf/data/neutrino/pdune/spine/train/vd/mpvmpr_v0/weights/grappa_track/edep/snapshot-*.ckpt
  #model.weight_path: /sdf/data/neutrino/pdune/spine/train/vd/mpvmpr_v0/weights/grappa_track/edep/snapshot-1[4-9][0-9]99.ckpt
  model.weight_path: /sdf/data/neutrino/pdune/spine/train/vd/mpvmpr_v0/weights/grappa_track/edep/snapshot-2[0-9][0-9]99.ckpt
