# Post-processing common configuration for generic simulations

__meta__:
  kind: fragment

# Run post-processors
post:
  stages:
    - name: shape_logic
      enforce_pid: true
      enforce_primary: true
    - name: direction
      obj_type: particle
      optimize: true
      run_mode: both
    - name: calo_ke
      scaling: 1.0
      shower_fudge: 1/0.83
    - name: csda_ke
      tracking_mode: step_next
      segment_length: 5.0
    - name: mcs_ke
      tracking_mode: bin_pca
      segment_length: 5.0
    - name: containment
      margin: 5.0
      mode: meta
    - name: vertex
      use_primaries: true
      update_primaries: false
    - name: topology_threshold
      ke_thresholds:
        4: 50
        default: 25
    - name: fiducial
      margin: 25.0
      mode: meta
    - name: children_count
      mode: shape
    - name: match
      match_mode: both
      ghost: false
      fragment: false
      particle: true
      interaction: true
