# Configuration which turns input SPINE data HDF5 files into Lite output HDF5 files
# This configuration works for any detector

__meta__:
  kind: bundle
  description: "Convert SPINE data HDF5 files to lite-output HDF5 files"

include: litify.yaml

override:
  # Remove truth information from the output
  io.writer.keys-:
    - truth_particles
    - truth_interactions

  # Build output representations without truth information
  build.mode: reco
