__meta__:
  kind: fragment
  version: "240719"
  date: "2024-07-19"
  description: 2x2 240719 standalone graph_spice

include: model/common/graph_spice/base_v1.yaml

override:
  model.modules.graph_spice: !include model/2x2/graph_spice/network_240719.yaml
  model.modules.graph_spice_loss: !include model/2x2/graph_spice/loss_240819.yaml
