# UResNet loss configuration used for deghosting
# Revision date: July 18, 2024

__meta__:
  version: "240718"
  date: "2024-07-18"
  description: "UResNet loss configuration for deghosting, July 2024"
  tags: []

include: uresnet_loss_common.yaml
