# Post-processing configuration for SBND
# Revision date: May 1, 2026

__meta__:
  kind: bundle
  version: "260501"
  date: "2026-05-01"
  description: "SBND post-processing, latest"
  compatible_with:
    base: ">=240720"
    io: ">=240720"
    model: ">=240720"
  tags: [normalized-fm, shower-pp]

include: post_common.yaml

override:
  # Cathode crosser configuration
  post.stages~:
    - update:
        name: direction
        changes:
          radius: 60.0
    - insert:
        before: shape_logic
        value:
          name: cathode_crosser
          run_mode: reco
          crossing_point_tolerance: 15
          offset_tolerance: 15
          angle_tolerance: 0.26
          merge_crossers: true
          adjust_crossers: false
          adjust_method: distance
    - insert:
        before: shape_logic
        value:
          name: time_containment
          logical: true
          mode: source
          margin: 0.0
          cathode_margin: -5.0
          exclude_pids:
            - 0
            - 1
          min_particle_sizes: 25
    - insert:
        before: vertex
        value:
          name: flash_match
          flash_key: flashes
          volume: module
          method: likelihood
          cfg: !path infer/sbnd/post/flashmatch/flashmatch_250408.cfg
          scaling: 1./555.
          alpha: 0.21
          recombination_mip: 0.6
          max_cathode_offset: 5
          time_contained: true
          merge:
            threshold: 1.0
            window:
              - -2.0
              - 2.0
            combine_volumes: true
          update_flashes: false
    - insert:
        before: topology_threshold
        value:
          name: mcs_ke
          run_mode: reco
          tracking_mode: bin_pca
          segment_length: 14.0
          fill_per_pid: true
          res_a: 0.21265598
          res_b: 1.40789473
          res_mixture: true
          res_weight_ratio: 1.0
          res_scale_ratio: 2.5
    - insert:
        before: topology_threshold
        value:
          name: containment
          run_mode: both
          mode: source
          margin: 5.0
          cathode_margin: -5.0
          exclude_pids:
            - 0
            - 1
    - insert:
        after: match
        value:
          name: start_dedx
          radius: 3.0
          mode: default
    - insert:
        after: start_dedx
        value:
          name: end_dedx
          radius: 4.0
          mode: default
          include_pids:
            - 2
            - 3
            - 4
    - insert:
        after: end_dedx
        value:
          name: start_straightness
          radius: 3.0
          n_components: 3
    - insert:
        after: start_straightness
        value:
          name: particle_spread
          start_mode: start_point
          use_start_dir: false
    - insert:
        after: particle_spread
        value:
          name: shower_conversion_distance
          mode: vertex_to_points
