# Post-processing common configuration for SBND

__meta__:
  kind: fragment

# Post-processors
post:
  stages:
    - name: direction
      obj_type: particle
      optimize: true
      run_mode: both
    - name: shape_logic
      enforce_pid: true
      enforce_primary: true
    - name: vertex
      use_primaries: true
      update_primaries: false
      update_orientations: true
      run_mode: reco
    - name: calo_ke
      run_mode: both
      scaling: 1.0
      shower_fudge: 1.306
    - name: csda_ke
      run_mode: reco
      tracking_mode: step_next
      segment_length: 5.0
      fill_per_pid: true
    - name: topology_threshold
      ke_thresholds:
        4: 50
        default: 25
    - name: fiducial
      mode: module
      margin:
        - - 20
          - 20
        - - 20
          - 20
        - - 10
          - 50
    - name: children_count
      mode: shape
    - name: match
      match_mode: both
      ghost: true
      truth_point_mode: points
      fragment: false
      particle: true
      interaction: true
