# Generic truth saving configuration
# Revision date: August 5, 2024

include:
  - base/base_240718.yaml
  - io/io_240805.yaml

# Overrides
override:
  # Only build truth objects
  build.mode: truth

  # No reconstructed information to write
  io.writer.keys-: [points, depositions, reco_particles, reco_interactions]
