__meta__:
  kind: fragment
  version: "260210"
  date: "2026-02-10"
  description: ProtoDUNE-SP 260210 standalone interaction GrapPA model

include: model/common/grappa_inter/base_v1.yaml

override:
  model.modules.grappa: !include model/protodune-sp/grappa_inter/network_260210.yaml
  model.modules.grappa_loss: !include model/protodune-sp/grappa_inter/loss_260210.yaml
