__meta__:
  kind: fragment
  version: "240819"
  date: "2024-08-19"
  description: ND-LAr 240819 standalone interaction GrapPA model

include: model/common/grappa_inter/base_v1.yaml

override:
  model.modules.grappa: !include model/nd-lar/grappa_inter/network_240819.yaml
  model.modules.grappa_loss: !include model/nd-lar/grappa_inter/loss_240819.yaml
