# DUNE10kt-1x2x6 full chain configuration
# Revision date: May 10, 2026

__meta__:
  kind: bundle
  version: "260510"
  date: "2026-05-10"
  description: "DUNE10kt-1x2x6 full chain configuration"

include:
  - base/base_260202.yaml
  - io/io_260202.yaml
  - model/model_260510.yaml
  - post/post_260202.yaml
