# DUNE10kt-1x2x6 full chain configuration
# Revision date: February 2, 2026

__meta__:
  kind: bundle
  version: "260202"
  date: "2026-02-02"
  description: "DUNE10kt-1x2x6 full chain configuration"

include:
  - base/base_260202.yaml
  - io/io_260202.yaml
  - model/model_260202.yaml
  - post/post_260202.yaml
