__meta__:
  kind: mod
  name: joint
  version: "240805"
  date: "2024-08-05"
  description: Generic primary/secondary joint-dataset inference
  applies_to: [mc]
  conflicts_with: [data, ovl]
  compatible_with:
    io: ">=240805"

include: mod_joint_common.yaml

override:
  io.loader.dataset.base.schema.ppn_label.include_point_tagging: false
