__meta__:
  kind: fragment
  version: "250515"
  date: "2025-05-15"
  description: ND-LAr 250515 standalone track GrapPA model

include: model/common/grappa_track/base_v1.yaml

override:
  model.modules.grappa: !include model/nd-lar/grappa_track/network_250515.yaml
  model.modules.grappa_loss: !include model/nd-lar/grappa_track/loss_240819.yaml
