__meta__:
  kind: fragment
  version: "240819"
  date: "2024-08-19"
  description: ND-LAr 240819 track GrapPA network used with the 2x2 debug model

include: model/common/grappa_track/network_v1.yaml

override:
  graph.max_length: 67
  node_encoder.dir_max_dist: -1
  node_encoder.dedx_max_dist: -1
