__meta__:
  kind: fragment
  version: "250505"
  date: "2025-05-05"
  description: ND-LAr 250505 track GrapPA network for full-chain aggregation

include: model/nd-lar/grappa_track/network_250505.yaml

override:
  nodes.make_groups: true
  nodes.grouping_method: score
