# UResNet model configuration used for deghosting
num_input: 2
num_classes: 2
filters: 32
depth: 5
reps: 2
allow_bias: false
activation:
  name: lrelu
  negative_slope: 0.33
norm_layer:
  name: batch_norm
  eps: 0.0001
  momentum: 0.01
