__meta__:
  kind: fragment
  version: "240718"
  date: "2024-07-18"
  description: Generic 240718 track GrapPA network

include: model/common/grappa_track/network_v1.yaml

override:
  node_encoder.dir_max_dist: -1
  node_encoder.dedx_max_dist: -1
