__meta__:
  kind: mod
  name: mpvmpr
  version: "260924"
  date: "2026-09-24"
  description: Interpret ND-LAr DLPGenerator MPV/MPR truth without neutrino objects
  applies_to: [mc]
  compatible_with:
    io: ">=240819"

include: mod_mpvmpr_common.yaml
