#SBND Charge Scale Function Variation
#Revision Date: August 13, 2026

__meta__:
  kind: mod
  name: "chargescale"
  version: "260813"
  date: "2026-08-13"
  description: "Charge Scale Function Variation"
  applies_to: [mc]
  compatible_with:
    post: ">=240720"

override:
  model.network_input.meta: meta
  
  model.modules.chain.calibration: apply
  model.modules.calibration:
    stage: segmentation
    response:
      response_func: 1.00582*x - 0.0001188*x*x - 4.4164e-8*x*x*x + 1.04071e-11*x*x*x*x