__meta__:
  kind: fragment
  version: "250505"
  date: "2025-05-05"
  description: ND-LAr 250505 Graph-SPICE network

include: model/common/graph_spice/network_v1.yaml

override:
  embedder.uresnet.spatial_size: 6144
  constructor.graph:
    name: radius
    r: 1.9
