# ND-LAr model configuration
# Revision date: May 5, 2025

__meta__:
  kind: bundle
  version: "250505"
  date: "2025-05-05"
  description: "ND-LAr model first full weights release"
  compatible_with:
    base: ">=240819"
    io: ">=240819"
  tags: []
  training_set: "v0"

include: model/nd-lar/full_chain/model_250505.yaml

override:
  # MPV/MPR v00 balanced kaon weight path
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/nd-lar/nd-lar_snapshot_250505.ckpt
    hash: c3176783a91889c69e4a7a4a05be7519ab0673ebc7042c930513f601b1365213
