# ND-LAr model configuration
# Revision date: March 10, 2026

__meta__:
  kind: bundle
  version: "260310"
  date: "2026-03-10"
  description: "ND-LAr model first full weights release"
  compatible_with:
    base: ">=240819"
    io: ">=240819"
  tags: []
  training_set: "v1"

include: model/nd-lar/full_chain/model_260310.yaml

override:
  # MPV/MPR v01 long-range, kaon weights path
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/nd-lar/nd-lar_snapshot_260310.ckpt
    hash: e0c896f516187add73dadb4c20e276d8dc07c9be434cbfb4930dfb6da2517178
