# ND-LAr model configuration
# Revision date: August 19, 2024

__meta__:
  kind: bundle
  version: "240819"
  date: "2024-08-19"
  description: "ND-LAr model 2x2 weights (debug)"
  compatible_with:
    base: ">=240819"
    io: ">=240819"
  tags: []
  training_set: "2x2_v2"

include: model/nd-lar/full_chain/model_240819.yaml

override:
  # 2x2 (!!!) MPV/MPR v02 default weights
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/2x2/2x2_snapshot_240819.ckpt
    hash: a0d5609e24abe8e88884d39ea6c0fcf4b507141bbc637fdf200cb404dfbd1bb0
