# ND-LAr model configuration
# Revision date: August 6, 2025

__meta__:
  kind: bundle
  version: "250806"
  date: "2025-08-06"
  description: "ND-LAr model first full weights release"
  compatible_with:
    base: ">=240819"
    io: ">=240819"
  tags: []
  training_set: "v0"

include: model/nd-lar/full_chain/model_250806.yaml

override:
  # MPV/MPR v00 overlay kaon weight path
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/nd-lar/nd-lar_snapshot_250806.ckpt
    hash: f8555a00f1833fc40235d37f3b346b77cf99ce0c0c4f29ddc3beb4362b0d1a39
