# ND-LAr model configuration
# Revision date: April 09, 2026

__meta__:
  kind: bundle
  version: "260409"
  date: "2026-04-09"
  description: "ND-LAr model first full weights release"
  compatible_with:
    base: ">=240819"
    io: ">=240819"
  tags: []
  training_set: "v1"

include: model/nd-lar/full_chain/model_260409.yaml

override:
  # MPV/MPR v01 long-range, kaon weights path, trained longer
  model.weight_path: !download
    url: https://s3df.slac.stanford.edu/data/neutrino/spine/weights/nd-lar/nd-lar_snapshot_260409.ckpt
    hash: 4b9cbe81a1fd8a757b374e177b5317647e5ff19ce201f9261a8ddae2c62c0233
