__meta__:
  kind: fragment
  description: SPINE v1 shower GrapPA loss

node_loss:
  provider: shower_primary
  high_purity: true
  use_closest: true
  use_group_pred: true
edge_loss:
  provider: channel
  target: group
  high_purity: true
