# SBND full chain configuration
# Revision date: May 1, 2026

__meta__:
  kind: bundle
  version: "260501"
  date: "2026-05-01"
  description: "SBND full chain configuration"

include:
  - base/base_260501.yaml
  - io/io_260218.yaml
  - model/model_co_260501.yaml
  - post/post_260501.yaml
