# Example ICARUS Production Pipeline
# This demonstrates a two-stage pipeline: reconstruction followed by analysis

stages:
  # Stage 1: Run SPINE reconstruction on raw data
  - name: reconstruction
    config: infer/icarus/latest_data.cfg
    files: /sdf/data/neutrino/icarus/run2/data/*.root
    profile: s3df_ampere
    ntasks: 100
    files_per_task: 1
    output: output_reco/icarus_reco.h5
    flashmatch: true
    # Clean up reconstruction output after analysis completes
    # This saves disk space by removing intermediate files
    cleanup:
      - output_reco

  # Stage 2: Run analysis on reconstructed data
  # This stage depends on reconstruction completing successfully
  - name: analysis
    depends_on: [reconstruction]
    config: infer/icarus/analysis.cfg
    files: output_reco/*.h5
    profile: s3df_milano
    ntasks: 20
    files_per_task: 5
    output: output_analysis/icarus_analysis.h5
