__meta__:
  kind: fragment
  description: SPINE v1 interaction GrapPA loss

node_loss:
  type:
    provider: class
    target: pid
    loss: ce
    balance_loss: true
  primary:
    provider: class
    target: inter_primary
    loss: ce
    balance_loss: true
  orient:
    provider: orient
    loss: ce
edge_loss:
  provider: channel
  target: interaction
