__meta__:
  kind: bundle
  version: "260310"
  date: "2026-03-10"
  description: ND-LAr March 2026 shower GrapPA training from cached fragment graphs

include:
  - model/nd-lar/grappa_shower/model_260310.yaml
  - train/nd-lar/grappa_shower/from_fragment_cache_v1.yaml
