__meta__:
  kind: bundle
  version: "250505"
  date: "2025-05-05"
  description: ND-LAr May 2025 shower GrapPA training from cached fragment graphs

include:
  - model/nd-lar/grappa_shower/model_250505.yaml
  - train/nd-lar/grappa_shower/from_fragment_cache_v1.yaml
