__meta__:
  kind: fragment
  version: "240718"
  date: "2024-07-18"
  description: Generic 240718 shower GrapPA loss

include: model/common/grappa_shower/loss_v1.yaml

override:
  node_loss.use_closest: false
