__meta__:
  kind: bundle
  version: "261007"
  date: "2026-10-07"
  description: 2x2 current candidate full chain on v2 data

include:
  - base/base_240719.yaml
  - io/io_240819.yaml
  - model/model_261007.yaml
  - post/post_240719.yaml
