__meta__:
  kind: fragment
  version: "260906"
  date: "2026-09-06"
  description: ProtoDUNE-SP 260906 standalone Graph-SPICE model

include: model/common/graph_spice/base_v1.yaml

override:
  model.modules.graph_spice: !include model/protodune-sp/graph_spice/network_260906.yaml
  model.modules.graph_spice_loss: !include model/protodune-sp/graph_spice/loss_260210.yaml
