__meta__:
  kind: fragment
  description: 2x2 grappa_shower training policy; provisional example resource sizes

include: train/common/grappa_shower/base_v1.yaml

override:
  io.loader.num_workers: 8
  io.loader.minibatch_size: 256
  io.loader.dataset.schema.data.particle_info.particle_event: particle_pcluster
  io.loader.dataset.schema.coord_label.particle_event: particle_pcluster
