# UResNet model + loss configuration for deghosting
# Revision date: January 18, 2026

__meta__:
  version: "260118"
  date: "2026-01-18"
  description: "UResNet model + loss configuration for deghosting in ProtoDUNE-VD, January 2026"
  tags: []

include: model/common/uresnet_deghost/uresnet_deghost_240718.yaml
