__meta__:
  kind: fragment
  version: "260210"
  date: "2026-02-10"
  description: ProtoDUNE-SP 260210 composed UResNet-PPN network

uresnet: !include model/protodune-sp/uresnet/network_260210.yaml
ppn: !include model/common/uresnet_ppn/ppn_v1.yaml
