__meta__:
  kind: fragment
  description: Run 2x2 inference on a primary/secondary joint dataset

override:
  io.loader.dataset:
    name: joint
    base: !include infer/2x2/io/dataset_joint.yaml
    primary:
      file_keys: null
    secondary:
      file_keys: null

  io.writer.keys-:
    - run_info
    - trigger
    - flashes
