# SLURM Resource Profiles for SPINE Production
# Define common resource configurations for different use cases

profiles:
  # Large GPU jobs (fastest, default) at S3DF
  # This is used to optimize batch sizes for training and inference.
  # Node resources: 4 GPUs, 112 CPUs, 952 GB RAM
  # -> 28 CPU per GPU, 8 GB per CPU
  s3df_ampere:
    partition: ampere
    gpu_type: a100
    gpu_mem: 40g
    gpus: 1
    cpus_per_task: 28
    mem_per_cpu: 8g
    time: "2:00:00"
    description: "High-performance GPU processing on Ampere partition"

  # Smaller GPU jobs (cheaper) at S3DF
  # Node resources: 10 GPUs, 40 CPUs, 160 GB RAM
  # -> 4 CPUs per GPU, 4 GB per CPU
  s3df_turing:
    partition: turing
    gpu_type: geforce_rtx_2080_ti
    gpu_mem: 11g
    gpus: 1
    cpus_per_task: 4
    mem_per_cpu: 4g
    time: "2:00:00"
    description: "Cheap GPU inference on Turing partition"
  
  # CPU-only analysis at S3DF Milano
  # Node resources: 120 CPUs, 480 GB RAM
  # -> 4 GB per CPU
  s3df_milano:
    partition: milano
    gpu_type: null
    gpu_mem: null
    gpus: 0
    cpus_per_task: 1
    mem_per_cpu: 4g
    time: "2:00:00"
    description: "CPU-only analysis tasks"

  # CPU-only analysis at S3DF Roma
  # Node resources: 120 CPUs, 480 GB RAM
  # -> 4 GB per CPU
  s3df_roma:
    partition: roma
    gpu_type: null
    gpu_mem: null
    gpus: 0
    cpus_per_task: 1
    mem_per_cpu: 4g
    time: "2:00:00"
    description: "CPU-only analysis tasks"
  
# Detector-specific defaults
detectors:
  icarus:
    default_profile: s3df_ampere
    configs_dir: config/icarus
    account: "neutrino:icarus-ml"
  
  sbnd:
    default_profile: s3df_ampere
    configs_dir: config/sbnd
    account: "neutrino:icarus-ml"
  
  2x2:
    default_profile: s3df_ampere
    configs_dir: config/2x2
    account: "neutrino:dune-ml"

  2x2-single:
    default_profile: s3df_ampere
    configs_dir: config/2x2-single
    account: "neutrino:dune-ml"

  fsd:
    default_profile: s3df_ampere
    configs_dir: config/fsd
    account: "neutrino:dune-ml"
  
  nd-lar:
    default_profile: s3df_ampere
    configs_dir: config/nd-lar
    account: "neutrino:dune-ml"
  
  generic:
    default_profile: s3df_ampere
    configs_dir: config/generic
    account: "neutrino:ml-dev"
  
  common:
    default_profile: s3df_milano
    configs_dir: config/common
    account: "neutrino:ml-dev"

# Default settings
defaults:
  account: "neutrino:ml-dev"
  max_array_size: 99
  files_per_task: 1
  output_dir: output
  log_dir: batch_logs
