# ProtoDUNE-VD truth conversion configuration
# Revision date: January 18, 2026

__meta__:
  kind: bundle
  version: "260118"
  date: "2026-01-18"
  description: "ProtoDUNE-VD LArCV-to-SPINE truth conversion configuration"

include:
  - infer/protodune-vd/base/base_260118.yaml
  - infer/protodune-vd/io/io_260118.yaml

# Overrides
override:
  # Only build truth objects
  build.mode: truth

  # Force CPU execution for truth-only parsing
  base.world_size: 0

  # Temporary workaround until SPINE produces sources labels without reco
  # No reconstructed information or wire-TPC-only source products to write
  io.writer.keys-:
    [
      points,
      depositions,
      reco_particles,
      reco_interactions,
      sources,
      sources_label,
    ]
