__meta__:
  kind: bundle
  version: "240718"
  date: "2024-07-18"
  description: Generic interaction GrapPA training benchmark with 64-wide GNN layers

include:
  - model/generic/grappa_inter/model_240718.yaml
  - train/generic/grappa_inter/base_v1.yaml
