# SBND forward SCE map variation
# Revision date: August 13, 2026

__meta__:
  kind: mod
  name: "forward_scemap"
  version: "260813"
  date: "2026-08-13"
  description: "Apply forward SCE map variation"
  applies_to: [mc]
  compatible_with:
    post: ">=240720"

override:
  model.network_input.meta: meta
  
  model.modules.chain.calibration: apply
  model.modules.calibration:
    stage: segmentation
    field:
      map_file: $SBND_DATA/v01_42_00/SCEoffsets/SCEoffsets_SBND_E500_dualmap_voxelTH3.root
      map_prefix: TrueFwd_Displacement
      map_suffixes: [_E, _W]
      map_selection_axis: 0
      map_selection_boundaries: [0.0]