__meta__:
  kind: fragment
  version: "260828"
  date: "2026-08-28"
  description: Generic standalone interaction GrapPA model without fragment disambiguation

include: model/common/grappa_inter/base_v1.yaml

override:
  model.modules.grappa.gnn_model.edge_layer.mlp.width: 128
  model.modules.grappa.gnn_model.node_layer.message_mlp.width: 128
  model.modules.grappa.gnn_model.node_layer.aggr_mlp.width: 128
