__meta__:
  kind: fragment
  version: "240805"
  date: "2024-08-05"
  description: Generic interaction GrapPA model revision with 128-wide GNN layers

include: model/common/grappa_inter/base_v1.yaml

override:
  model.modules.grappa: !include model/generic/grappa_inter/network_240805.yaml
  model.modules.grappa_loss: !include model/generic/grappa_inter/loss_240805.yaml
