__meta__:
  kind: fragment
  version: "240718"
  date: "2024-07-18"
  description: Generic 240718 interaction GrapPA network with 64-wide GNN layers

include: model/common/grappa_inter/network_v1.yaml

override:
  node_encoder.dir_max_dist: -1
  node_encoder.dedx_max_dist: -1
  gnn_model.edge_layer.mlp.width: 64
  gnn_model.node_layer.message_mlp.width: 64
  gnn_model.node_layer.aggr_mlp.width: 64
