__meta__:
  kind: fragment
  description: Default standalone UResNet semantic-segmentation model

model:
  name: uresnet
  weight_path: null

  network_input:
    data: data

  loss_input:
    seg_label: seg_label

  modules:
    uresnet: !include network.yaml
    uresnet_loss: !include loss.yaml
