__meta__:
  kind: bundle
  version: "240718"
  date: "2024-07-18"
  description: Generic 240718 shower GrapPA training from cached fragment graphs

include:
  - model/generic/grappa_shower/model_240718.yaml
  - train/generic/grappa_shower/from_fragment_cache_v1.yaml
