__meta__:
  kind: fragment
  description: Common generic simulation LArCV inference dataset

provider: larcv
file_keys:
schema:
  data:
    provider: sparse3d
    sparse_event: sparse3d_pcluster
  seg_label:
    provider: sparse3d
    sparse_event: sparse3d_pcluster_semantics
  ppn_label:
    provider: particle_points
    sparse_event: sparse3d_pcluster
    particle_event: particle_corrected
    # include_point_tagging varies by config - override in specific configs
  clust_label:
    provider: cluster3d
    cluster_event: cluster3d_pcluster
    particle_event: particle_corrected
    sparse_semantics_event: sparse3d_pcluster_semantics
    add_particle_info: true
    clean_data: true
    shape_precedence: [2, 1, 0, 3, 4, 6]
  coord_label:
    provider: particle_coords
    particle_event: particle_corrected
    cluster_event: cluster3d_pcluster
  graph_label:
    provider: particle_graph
    particle_event: particle_pcluster
  particles:
    provider: particle
    particle_event: particle_pcluster
    cluster_event: cluster3d_pcluster
  meta:
    provider: meta3d
    sparse_event: sparse3d_pcluster
  run_info:
    provider: run_info
    sparse_event: sparse3d_pcluster
