# IO common configuration for generic simulations

__meta__:
  kind: fragment

# IO configuration
io:
  loader:
    batch_size: 64
    shuffle: false
    num_workers: 8
    collate_fn: all
    dataset: !include dataset_common.yaml
  writer:
    name: hdf5
    file_name: null
    overwrite: true
    keys:
      - run_info
      - meta
      - points
      - points_label
      - depositions
      - depositions_label
      - reco_particles
      - truth_particles
      - reco_interactions
      - truth_interactions
