__meta__:
  kind: fragment
  description: Run ICARUS inference on a primary/secondary joint dataset

override:
  io.loader.dataset:
    name: joint
    base: !include infer/icarus/io/dataset_joint.yaml
    primary:
      file_keys: null
    secondary:
      file_keys: null

  io.writer.keys-:
    - run_info
    - flashes
    - crthits

  post-: flash_match
