__meta__:
  kind: mod
  name: joint
  version: "240812"
  date: "2024-08-12"
  description: ICARUS primary/secondary joint-dataset inference
  applies_to: [mc]
  conflicts_with: [data, numi, single]
  compatible_with:
    io: ">=240812"

include: mod_joint_common.yaml

override:
  io.loader.dataset.base.schema.ppn_label.include_point_tagging: false
