__meta__:
  kind: bundle
  version: "240718"
  date: "2024-07-18"
  description: Generic track GrapPA training from cached 240805 fragments

include:
  - model/generic/grappa_track/model_240718.yaml
  - train/generic/grappa_track/from_fragment_cache_v1.yaml
