__meta__:
  kind: fragment
  version: "240805"
  date: "2024-08-05"
  description: Generic UResNet-PPN model revision without endpoint classification

include: model/common/uresnet_ppn/base_v1.yaml

override:
  model.modules.uresnet: !include model/generic/uresnet/network_240718.yaml
  model.modules.ppn: !include model/generic/uresnet_ppn/ppn_240805.yaml
  model.modules.uresnet_loss: !include model/generic/uresnet/loss_240718.yaml
  model.modules.ppn_loss: !include model/generic/uresnet_ppn/ppn_loss_240805.yaml
