__meta__:
  kind: fragment
  version: "240718"
  date: "2024-07-18"
  description: Generic UResNet-PPN model revision with endpoint classification

include: model/common/uresnet_ppn/base_v1.yaml

override:
  model.modules.ppn.classify_endpoints: true
  model.modules.ppn_loss.restrict_to_clusters: false
